### ISSUE TITLE
Meeting

### ISSUE THREAD

**Issue by mauigna06** [SlicerIGT/SlicerBoneReconstructionPlanner#21]
Hi @lassoan and @cmfsx . I would like to schedule a meeting to talk about how the project should follow, how the module should change to be possible to make surgical guides in it. When are you available?

**Comment by cmfsx** [comment]
The usual time we have meetings is fine for me as it is night here.

**Comment by mauigna06** [comment]
Okey, so 2pm EST. Andras when are you available?

**Comment by mauigna06** [comment]
@lassoan, when could you meet?

**Comment by lassoan** [comment]
Today between 1-3pm or Monday any time works for me.

**Comment by mauigna06** [comment]
Okey Andras. We'll do it today at 2pm EST through Skype

**Comment by lassoan** [comment]
As discussed, I've made vtkbool available in Slicer. Install Sandbox extension, it has a new module: [CombineModels](https://github.com/PerkLab/SlicerSandbox/tree/master/CombineModels ).

See example of how to use it here:
https://github.com/PerkLab/SlicerSandbox/blob/476e3d67a4ed90176825db8cf03cf7d82f7b6f2a/CombineModels/CombineModels.py#L357-L373

@mauigna06 Please add the other ideas and tasks that we talked about (to make sure we don't forget about them). Thank you!

**Comment by mauigna06** [comment]
Notes from the meeting of 05/02:
- No use of ctkworkflow
- Spinbox or slider for intersection position with valueChangedEvent to update the fibula planes
- Two 3d views -> one above the slices, one horizontal below the slices
Displaynode of models and planes -> viewnodeid set up to only show the node in one view
- Reorder planes on mandiblePlaneList automatically so that mandiblePlanes can be created between other mandiblePlanes without problems
- Switch off the snapping so you can create mandibleCurve points on empty space
- Document how to put mandiblePlanes: you should put the first point of the mandiblePlane over the mandibleModel where is nearest to the point of the mandibleCurve you want the mandiblePlane
- All these above is for later because it doesn't have priority
- Procedure to create surgicalGuideBaseModel starting from a segmentation of the fibula: hollow 6mm, scissors, keep largest island, create 3d model
- Proposal for a grant will be made in June for a clinical study @cmfsx 
- [ ]  Integrate vtkbool to the module @lassoan

Changes that @mauigna06 should work on next:

- [ ]  fibulaPlanes to sawBoxes. Create each box of the size you desire then transform it with vtktransformpolydatafilter to the position and orientation fibulaPlane has.
- [ ]  add cylinders over the positions of a fiducial list and with the normal the surgicalGuideBaseModel.  Get the normals of the model. Get the closest point of the model to a fiducial and with its index get its normal.

Please add anything you think I may have forgotten

I had problems changing the GUI, I couldn't make CollapsibleGroupBoxes show well so I stuck to the layout we have been using

**Comment by lassoan** [comment]
> I had problems changing the GUI, I couldn't make CollapsibleGroupBoxes show well so I stuck to the layout we have been using

What kind of problems?
By the way, we rarely use collapsible groupbox, but instead most commonly ctkCollapsibleButton is used.

**Comment by mauigna06** [comment]
Here is an example of the problems I get with ctkCollapsibleButton:
![GUI_problem](https://user-images.githubusercontent.com/19158307/107155352-b0d84700-6956-11eb-9a1f-aa4c5a876270.png)

**Comment by lassoan** [comment]
This looks good, you just haven't defined a layout for the widget. After you drag-and-drop a widget into any other widget, you need to right-click on the parent widget and select a layout.

**Comment by mauigna06** [comment]
@lassoan, should we wait to after the pull request is approved to make the next meeting? I want to talk about how I plan to create the sawBoxes for the mandibleSurgicalGuides

**Comment by lassoan** [comment]
I'm available, the pull request is merged, so we can have the meeting anytime that works for you.

**Comment by cmfsx** [comment]
Hi, is it possible to move the meeting to any date and time after or on
this Saturday? As on Thursday and Friday i am not in a position to join.
Basically I don't have access to work for this couple of days hence the
delay in doing the mandible guide base also.

**Comment by mauigna06** [comment]
I'm available also. So we can do it on Saturday at 2pm or 4pm EST, or on Monday at 2pm EST. 
@mrtig when are you available?

**Comment by mrtig** [comment]
I think both days 2 pm EST would be good. 4 pm would be a bit too late in my time zone.

**Comment by mauigna06** [comment]
Okey. So we meet Saturday 2pm EST.

**Comment by lassoan** [comment]
OK

**Comment by mauigna06** [comment]
Notes from meeting 06/03:

Work to be done ordered by priority:
- [ ] create GUI for the mandibleSurgicalGuides
- [ ] use mandibleCurve to get the other plane to use to get the point where the sawBox is going to be transformed to.
- [ ] connection piece for the mandibleSurgicalGuides made with an open curve and then extruded outward. Which module to use for this?
- [ ] use decimated models for interactive editing (fastQuadric decimation) and for boolean operations full resolution models
- [ ] combine 3 last buttons of the planning to be one. Use ctk.ctkCheckablePushButton()
- [ ] @lassoan will review the last pull request
- [ ] @mrtig will document the surgeries he planned using the module [here](https://github.com/lassoan/SlicerBoneReconstructionPlanner/discussions/new)
- [ ] @mrtig will post a scene where miterBoxes do not aling well

Maybes:
- use segment editor inside the module
- centerline capture

**Comment by cmfsx** [comment]
@mrtig 

It works well in my one. 

1. Load the mrml scene 
2. Click create bone models from segmentation once
3. Draw a direction line for the mitter boxes (Acrros the fibula)
4. select that line in the mitter box direction line drop down list
5. click create mitter boxes

![Screenshot from 2021-03-09 15-47-32](https://user-images.githubusercontent.com/57766971/110455894-f3747700-80ee-11eb-9ae4-29bb67499cf0.png)

**Comment by mauigna06** [comment]
It works the way @cmfsx explained.

I can see you are using old code. You should use the last code commited to the main branch (at least you can use the code that is loaded right now as a stable version).

The current code saves the bone models references on the parameter node, so this step:

> 2. Click create bone models from segmentation once

is no longer needed (with the updated code).

You can check the documentation on to how to create the miterBoxDirectionLine but basically is a line that goes from medial to lateral. After you created it you can play around a little bit with it to see how it changes the miterBoxes orientation

**Comment by mrtig** [comment]
Hi,

Yes, this was my misunderstanding. I drew the line parallel to the fibula.
I finally had some time to write about the guides I have made --> https://github.com/lassoan/SlicerBoneReconstructionPlanner/discussions/40
Please let me know what I should add to the writing.

**Comment by mauigna06** [comment]
Obtener Outlook para Android<https://aka.ms/ghei36>
________________________________

**Comment by mauigna06** [comment]
> I finally had some time to write about the guides I have made --> #40

Hi @mrtig. Thank you

> Please let me know what I should add to the writing.

Give me some time to read it and I'll make comments

**Comment by mauigna06** [comment]
Hi guys. The module is about to be incorporated to the extensionsIndex and it'll be good to talk about the future of the project. 
Are you available on monday or wednesday for a meeting?

**Comment by cmfsx** [comment]
I am available on both days

**Comment by lassoan** [comment]
Both days work for me, too.

**Comment by mauigna06** [comment]
So the meeting could be on monday 2pm EST. Please propose another time if it's not convenient to you

**Comment by lassoan** [comment]
Monday 2pm EST works for me.

**Comment by lassoan** [comment]
I have a meeting at 2pm EST. Would 1pm or 3pm work for you?

**Comment by cmfsx** [comment]
1 pm is better.

**Comment by mauigna06** [comment]
Okay. So monday 1pm EST. See you guys

**Comment by mauigna06** [comment]
On project week I'll working on making dental implant planning possible and corresponding changes to the fibula surgical guide.

I'd like to have a meeting to talk about the design

@lassoan, @cmfsx, @mrtig are you available preferably tomorrow, or Tuesday?

**Comment by cmfsx** [comment]
> On project week I'll working on making dental implant planning possible and corresponding changes to the fibula surgical guide.
> 
> I'd like to have a meeting to talk about the design
> 
> @lassoan, @cmfsx, @mrtig are you available preferably tomorrow, or Tuesday?

Please suggest a time I can make myself available depending on time on both days.

**Comment by mrtig** [comment]
I think today from 12 PM to 3 PM EST and tomorrow from 9 AM to 3 PM EST.

**Comment by mauigna06** [comment]
@lassoan sorry for the late meeting organizaron. I know you are very busy these days. 
Any chance you could get 30min to talk about implant planning design?

**Comment by cmfsx** [comment]
I can make it at 1 pm EST today or 2pm est tomorrow

**Comment by mauigna06** [comment]
@mrtig we are communicating through [discord](https://etsmtl.zoom.us/j/86211702920?pwd=TEl0ZTFDam90WVN5bjZhR05kNVRVZz09#success) because of [Project Week](https://projectweek.na-mic.org/PW35_2021_Virtual/). You can learn more on "Planar Osteotomies Virtual Surgical Planning And Patient-Specific Surgical Guides" project channel of discord.

**Comment by mrtig** [comment]
> @mrtig we are communicating through [discord](https://etsmtl.zoom.us/j/86211702920?pwd=TEl0ZTFDam90WVN5bjZhR05kNVRVZz09#success) because of [Project Week](https://projectweek.na-mic.org/PW35_2021_Virtual/). You can learn more on "Planar Osteotomies Virtual Surgical Planning And Patient-Specific Surgical Guides" project channel of discord.

I'm not quite sure how it would work. Will you have a presentation about your work and then Q&A?

**Comment by mauigna06** [comment]
Hi @mrtig. We are all participating on project week. Yesterday some team members of our project joined to a quick meeting to talk about dental implant planning design on discord. The meeting was organized spontaneously. It will be good of you join the discord server and look to our project channel to participate in new meetings or give your opinions to the topics we discuss there. Project week will last till Friday.

**Comment by mauigna06** [comment]
@mrtig we'll have a meeting in 30 minutes here: https://discord.gg/5TC5H2g63e on the "Planar Osteotomies Virtual Surgical Planning And Patient-Specific Surgical Guides" project channel of discord. It's on the 'IGT' category. Will be good if you join.

**Comment by mrtig** [comment]
@mauigna06 Sorry, I didn't see the message yesterday.

**Comment by mauigna06** [comment]
Hi @cmfsx, @lassoan and @mrtig. I would like us to have a meeting to talk about this project.

Are you available tomorrow 2pm (Buenos Aires time)? If not please propose another time/date

**Comment by lassoan** [comment]
It works for me.

**Comment by cmfsx** [comment]
It works for me as well

**Comment by mrtig** [comment]
I’ll also try to attend.

**Comment by mauigna06** [comment]
Hi @lassoan, @cmfsx and @mrtig 

For project week and to show you the advances of the automaticPlanning branch it would be great if we can have a meeting tomorrow from 8:30am to 9:30am ET.

Would you be able to attend?

**Comment by mauigna06** [comment]
Ok. So this was not organized with enough time ahead. What if we do one meeting Wednesday next week at 2pm (Buenos Aires Time)? I'll also invite two or three surgeons that use this software that we don't know yet.

@lassoan, @cmfsx We can do a meeting for project week on the afternoon (ET) if you want anyway

**Comment by mrtig** [comment]
All the times proposed times would be suitable for me. I have another case where I could try the automatic planning branch.

**Comment by mauigna06** [comment]
Thanks @mrtig I have not updated the code yet because I'm not sure of publishing it since it's something that nobody else has. So I have a working version that is not public yet. If we do a meeting I'll show you how it works. It's not perfect but I think it's quite good

**Comment by mrtig** [comment]
@mauigna06 , Shall we do it today at the time you first proposed? In 20 minutes.

**Comment by mauigna06** [comment]
@mrtig Let's push it to today 2pm ET (is this okey for you?) to see if someone else can come? If not it could be tomorrow at 8:30am ET

**Comment by cmfsx** [comment]
SOrry for late reply i am fine with today 2pm .

**Comment by mrtig** [comment]
@mauigna06 2 pm ET is ok with me, also tomorrow at 8.30.

**Comment by mauigna06** [comment]
The meeting will be done today in approx 3hrs. Please use this discord server: https://discord.gg/d5Q6b5ug8u

The meeting will happen on the "3D View" room
