### ISSUE TITLE
Preview video of the module uploaded

### ISSUE THREAD

**Issue by mauigna06** [SlicerIGT/SlicerBoneReconstructionPlanner#45]
Hi. I made a preview video of BoneReconstructionPlanner.

https://youtu.be/uwsYccYzBWs

Leave your comments here

**Comment by lassoan** [comment]
The video looks great! It would be important to add subtitles to explain each step. It would nice to show how the connecting curve can be added to the mandible cutting guide.

**Comment by cmfsx** [comment]
Very good @mauigna06.

**Comment by mauigna06** [comment]
> The video looks great! It would be important to add subtitles to explain each step. It would nice to show how the connecting curve can be added to the mandible cutting guide.

My objetive with the preview video was to show what BoneReconstructionPlanner was capable of without giving too much explanation because that would have made the video longer. 
I was thinking that a spoken videotutorial or a tutorial of use on a Wiki could be done. Do you think this is okey? Should the explanation be lengthy and detailed or short and general? I don't know how much tutorial support is given to Slicer extensions

If the previous is not necesary. Do you still want me to add subtitles to the preview? Considering it is a short video, explanations cannot be profound and there a lot of necesary steps that are not shown there. What do I do with that? Is okey to leave the user to figure things out by himself?

**Comment by lassoan** [comment]
The video length is good, it should not be longer, but we need to keep viewers engaged and convey more information by explaining what is happening and why by talking and/or subtitles.

**Comment by mauigna06** [comment]
Here is the video with me explaining: https://www.youtube.com/watch?v=aZzcJ2AFiMo

I hope is better. Let me know

**Comment by mauigna06** [comment]
Do you have any opinion on the new video?
Also I can show the mandible surgical guide with the bridge in a new version. Any other change you would like?

**Comment by cmfsx** [comment]
> Do you have any opinion on the new video?

It is good for the purpose and for the duration for someone who is familiar with the development of this kind of guide and plans. 

For clinicians, it will need to be supplemented with clinical information and rationales behind each step and this will not be possible with two minutes or so.

**Comment by lassoan** [comment]
> For clinicians, it will need to be supplemented with clinical information and rationales behind each step and this will not be possible with two minutes or so.

Very good point. A few-minute tutorial is very useful for a quick overview, and when @cmfsx has time he could create a long video from a clinician's perspective, for clinicians.

**Comment by mauigna06** [comment]
This is the final version of the preview video: 
https://youtu.be/wsr_g_1E_pw

Showing the bridge of the mandibleSurgicalGuide was added

**Comment by mauigna06** [comment]
Here is the short video for twitter: https://youtu.be/r5M1ObZuvPk

Tell me if you like it and I'll make the tweet.

**Comment by lassoan** [comment]
It is a good start, but try to add a bit more actions to it: not just slightly rotate a static scene, but show placement of the curve and planes, moving of a plane and automatically updating the bone pieces, showing how the surgical guide is created (cut planes, miter boxes, then the complete surgical guide), how the placement guide is created. It can be very dense, as it will be short and people can watch it repeatedly, you would also add a link to the discourse post, so that people could read more about it, watch the longer video, etc.

You can upload further drafts of the video here in the issue (you can attach mp4 files to github issues) and the final version should be uploaded to the Twitter post (because then the video is shown directly in Twitter).

**Comment by mauigna06** [comment]
> how the placement guide is created

What placement guide? Placement guides are possible but we have never made one. Only mandible surgical guide and fibula surgical guide

**Comment by lassoan** [comment]
> What placement guide? 

I meant the mandible cutting guide, sorry.

> Are you sure you want that?

Yes! It is like an advertisement or movie trailer. It should just give a glimpse of what the post is about. You need to grab the attention of the reader in a few seconds and it is not realistic to hold it for more than 10-20 seconds. The goal is to convince the reader to click on the link that provides more details, full video, etc.

Example of similar videos that I've made:
- https://twitter.com/lassoan/status/1376394823071113217
- https://twitter.com/lassoan/status/1337473324725710870
- https://twitter.com/lassoan/status/1332130916366508032
- https://twitter.com/lassoan/status/1274043058670231553
- https://twitter.com/lassoan/status/1327060103263096832
- https://twitter.com/lassoan/status/1152595940081045504

Most of the software I use are free, but I would highly recommend buying Camtasia from Techsmith. It is unique among all video editing software that it is very powerful yet it is very easy to use.

**Comment by lassoan** [comment]
@mauigna06 do you plan to create the short video? It would be great to give some visibility to your great work.

**Comment by mauigna06** [comment]
Yes @lassoan. I'm screenrecording and editing on the software you recommended. Is there a deadline to post this video? I think I could finish it in a few days.

**Comment by lassoan** [comment]
There is no deadline, whenever you have time is fine.

**Comment by mauigna06** [comment]
Here is the video. Tell me what you think of it.

https://user-images.githubusercontent.com/19158307/119189195-21acf600-ba52-11eb-982b-a587417e248a.mp4

Here is the text of the tweet: 
"New 3D Slicer extension for virtual surgical planning of mandibular reconstruction with vascularized fibula free flap and generation of patient-specific surgical guides
Learn more at: https://discourse.slicer.org/t/17638"

**Comment by lassoan** [comment]
This looks perfect! Small comment for the text: instead of `3D Slicer` use `@3DSlicerApp`, because this will add a link to 3D Slicer and will make your tweet visible for 3D Slicer twitter account managers.

**Comment by lassoan** [comment]
And one more little trick: twitter shows the first frame of the video as thumbnail. I would recommend to add a very nice still image (like the very last frame of the current video, just without the plane interaction arrows) to the very beginning of the video and show it for a half second.

**Comment by mauigna06** [comment]
Here is the final version of the video:

https://user-images.githubusercontent.com/19158307/119203227-eec22c80-ba68-11eb-905d-56353b7c791b.mp4

and the final text for the tweet:
"New @3DSlicerApp extension for virtual surgical planning of mandibular reconstruction with vascularized fibula free flap and generation of patient-specific surgical guides.
Learn more at: https://discourse.slicer.org/t/17638"

If no more changes are needed I'll make the tweet

**Comment by lassoan** [comment]
This looks perfect!

**Comment by mauigna06** [comment]
tweeted:
https://twitter.com/EngDominguez/status/1395875994725146639
