### ISSUE TITLE
SlicerRT is now a dependency of this module

### ISSUE THREAD

**Issue by mauigna06** [SlicerIGT/SlicerBoneReconstructionPlanner#46]
An SlicerRT filter, vtkCollisionDetectionFilter, is used to check the security margin between fibula pieces. You can also disable "Check security margin on miter box creation" and you will not need this dependency.
vtkCollisionDetectionFilter is available in preview releases of Slicer but I think our focus should be to give support to the stable release.

Other dependencies are:
Sandbox: CombineModels module used to make boolean operations between meshes to make the surgicalGuides
MarkupsToModel: used to create the mandibleBridge for mandibleSurgicalGuides
SurfaceWrapSolidify: Used to eliminate holes from bone segments. Needed for sawBoxes/miterBoxes positioning algorithm to work well.

I'll add this information to the readme shortly

**Comment by cmfsx** [comment]
@mauigna06 is it possible to make it auto-download all dependencies when we install this extension?  I have seen it with other extensions.

**Comment by mauigna06** [comment]
Yes. From what I've seen it's just a parameter configuration. No problem

**Comment by cmfsx** [comment]
Is it possible to make the error message more user-friendly and understandable? "The planned fibula segments overlap each other" (Security margin:XX). You can fix this by increasing the 'intersection distance multiplier' or 'between space' value.

**Comment by mauigna06** [comment]
> "The planned fibula segments overlaps each other" 
It is not exact to say there is overlap. Because the security margin could be 5mm and if fibula pieces are 4mm appart the error would show.

I could change it to this:
"Planned fibula segments could overlap each other (the distance in between them do not satisfy the security margin of XXmm). You can fix this by increasing 'intersection distance multiplier' or 'between space' and pressing the update button"
