### ISSUE TITLE
Fibula surgical guide generation is not working

### ISSUE THREAD

**Issue by mauigna06** [SlicerIGT/SlicerBoneReconstructionPlanner#47]
> Fibula surgical guide generation is not working. Nothing happens when the boolean operation button in fibula surgical guide generator is pressed.

Please @cmfsx do open a new issue when you have this kind of problems, comments on commits are not searcheable.

Open the python interactor. Press enter a few times to separe the previous messages. And press the button to make the fibula surgical guide. Does an error appear? if so, post it.
If not, is the time of processing in any step 0.00 if this happens it means that vtkbool failed to make the boolean operation and returned an empty model. You can check this by searching in the data module a model called "FibulaSurgicalGuidePrototype" and hovering the mouse over it will tell you the number of points the model has, it should say zero. I have solved this problem moving the miterBoxDirectionLine a little bit, creating the miterBoxes again and pressing the button to create the fibula surgical guide should work now.

**Comment by cmfsx** [comment]
Ok I gave it a closer inspection. The reason for this I find to be rather peculiar. I have in the case I reported have placed one fiducial point on 'air' and the cylinder was not going through the base. In this case, it failed to generate the surgical guide.  And when I adjusted the point so the cylinder intersects the base is successfully generated. Perhaps we can create a error message for this ? 

In the python interaction, no error messages were generated. 
In successful cases, we get longer processing times like "Processing completed in 8.88 seconds" and when it fails something like Processing completed in 0.04 seconds

![Screenshot_6](https://user-images.githubusercontent.com/57766971/117033948-7a755280-ad20-11eb-8092-a607031f2635.png)

**Comment by mauigna06** [comment]
> Perhaps we can create a error message for this ?

Okey. I cannot explain lengthly all the possible reasons of error when an empty model is created on the error-message because it will be too long.
I don't know how to be helpful to the user without writing a lot.
@lassoan is an error message like "Error: Boolean operations failed." enough?
