### ISSUE TITLE
Fibula Segment Length

### ISSUE THREAD

**Issue by cmfsx** [SlicerIGT/SlicerBoneReconstructionPlanner#48]
@mauigna06 
While planning the video,I remember that we have not implemented a basic feature. That is the length of each fibula segment.  This is one of the most important parameters for clinicians to avoid short segments and properly place the osteotomy cuts. 

Is it possible to display the fibula segment lengths with hide/unhide option ( to prevent cluttering of the 3D view) ? or as a separate table ?

**Comment by mauigna06** [comment]
@lassoan do you have any suggestion on how to implement this?

**Comment by lassoan** [comment]
You can draw a curve segment and enable "length" measurement. The length value is displayed on the curve along with the curve's name. The curve will be probably inside the fibula bone and so its points will be occluded, but you can enable occluded visibility to force the line and label appear anyway. There is a bug that in curves the occluded visibility is not applied to the property label, but I'll fix that tomorrow.

**Comment by mauigna06** [comment]
> You can draw a curve segment and enable "length" measurement. The length value is displayed on the curve along with the curve's name. The curve will be probably inside the fibula bone and so its points will be occluded, but you can enable occluded visibility to force the line and label appear anyway. There is a bug that in curves the occluded visibility is not applied to the property label, but I'll fix that tomorrow.

Okey. So I'll use a vtkMRMLMarkupsCurveNode with SetCurveTypeToLinear() and two control points for each bone segment. And I'll enable "length" measurement for each display node of the curves.
These curves would be shown/hidden with a button.

Maybe I should hide the text label of the fibula planes because the colors already identify them. So we have less text labels to clutter the fibula 3D view

**Comment by lassoan** [comment]
Sounds good. If it is a straight line then you can use a markups line node instead of a curve

**Comment by mauigna06** [comment]
The code has been updated. Now fibula pieces lengths are measured.

**Comment by mauigna06** [comment]
Fibula segment length should be measured:
- distal to distal
- proximal to proximal
- centroid to centroid (this one is the only one supported currently)

Probably the most appropiate widget to show this would be a table inside a dialog

**Comment by mauigna06** [comment]
> Probably the most appropiate widget to show this would be a table inside a dialog

It appears a QTableWidget below the "show/hide fibula segment lengths" button would be better than a dialog

**Comment by mauigna06** [comment]
> Fibula segment lengths is currently measured using the fibula planes intersection with the fibula bone:
> 
>     * calculating intersections centroid to centroid distance

@cmfsx, if the osteotomy angles are sharp you could get something like this:

![Captura desde 2023-07-04 17-10-29](https://github.com/SlicerIGT/SlicerBoneReconstructionPlanner/assets/19158307/ddd8ae1b-72f3-4ecd-a0d3-1316615028c7)

Here it's zoomed in:

![Captura desde 2023-07-04 17-10-41](https://github.com/SlicerIGT/SlicerBoneReconstructionPlanner/assets/19158307/01d2d596-4f78-4361-a0f0-0db23af52ded)

If you measure with a the line below _**S0**_ it will measure less than S0, if you measure with a line above _**S0**_ it will measure more than _**S0**_? What is the correct convention?

And how do you measure the segment length on the below configuration (i.e. with those osteotomies)?:

![Captura desde 2023-07-04 17-20-25](https://github.com/SlicerIGT/SlicerBoneReconstructionPlanner/assets/19158307/be70083b-8355-4aec-9552-87c1dd3810df)

![Captura desde 2023-07-04 17-20-35](https://github.com/SlicerIGT/SlicerBoneReconstructionPlanner/assets/19158307/631438f8-5c4c-43c1-a3dc-41ecaf89c280)

**Comment by mauigna06** [comment]
Dear @SteveMaisi

Could you provide an answer to [this question](https://github.com/SlicerIGT/SlicerBoneReconstructionPlanner/issues/48#issuecomment-1620701820) above :)

**Comment by SteveMaisi** [comment]
Hi. Normally I will measure the longest aspect of the fibula segments not the centroid distance. 
Reasons:
1.	it represents the true length of total fibula length to be harvested. At the same time can estimate the length of pedicle left for anastomosis planning purposes.
2.	Many surgeons have their own standard for shortest fibula segment cuts ranging 15mm to 30mm (based on studies) to reduce the risk of compromised blood supply. For me I will set 20mm. So important to measure the longest aspect of the fibula segments.

**Comment by mauigna06** [comment]
Thanks @SteveMaisi for your answer

So is it safe to say that on the picture below you'd measure (i.e. prefer) the largest segment-length that is parallel to the centerline?

![250985358-631438f8-5c4c-43c1-a3dc-41ecaf89c280](https://github.com/SlicerIGT/SlicerBoneReconstructionPlanner/assets/19158307/f8a13733-4e69-4295-8955-b8387effb0ee)

**Comment by SteveMaisi** [comment]
![image](https://github.com/SlicerIGT/SlicerBoneReconstructionPlanner/assets/97390689/a470c820-e1dc-41f6-a52c-b501cbefd5f8)
Yes. For example in this case the longest aspect located at the lower and outer surface of mandibular curvature.

**Comment by mauigna06** [comment]
Ok
Thanks :)

**Comment by mauigna06** [comment]
How fibula segments length is measured should be a setting, value would be:
- nearest to nearest
- centroid to centroid
- farthest to farthest

(all of them parallel to the centerline)
